import "./globals.css";
import ResponsiveAppBar from "../components/ResponsiveAppBar";

import { VT323 } from "@next/font/google";

const vtT323 = VT323({
  weight: "400", // You can specify different weights if needed
  subsets: ["latin"], // Specify the subset used
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="vt323-regular">
        <ResponsiveAppBar />
        {children}
      </body>
    </html>
  );
}
